// <auto-generated />
using System;
using KrishiEye.Services.Transport.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KrishiEye.Services.Transport.Infrastructure.Migrations
{
    [DbContext(typeof(TransportDbContext))]
    [Migration("20251127102044_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KrishiEye.Services.Transport.Domain.Entities.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("LicenseExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LicenseImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NidNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active");

                    b.Property<Guid>("TransporterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.HasIndex("TransporterId", "Status")
                        .HasDatabaseName("IX_Drivers_Transporter_Status");

                    b.ToTable("Drivers", (string)null);
                });

            modelBuilder.Entity("KrishiEye.Services.Transport.Domain.Entities.JobAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("IX_JobAssignments_Request");

                    b.HasIndex("VehicleId");

                    b.ToTable("JobAssignments", (string)null);
                });

            modelBuilder.Entity("KrishiEye.Services.Transport.Domain.Entities.TransportBid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BidTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.Property<Guid>("TransporterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_TransportBids_Status");

                    b.HasIndex("TransporterId");

                    b.HasIndex("RequestId", "TransporterId")
                        .IsUnique()
                        .HasDatabaseName("IX_TransportBids_Request_Transporter");

                    b.ToTable("TransportBids", (string)null);
                });

            modelBuilder.Entity("KrishiEye.Services.Transport.Domain.Entities.TransportRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DropAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoodsType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Open");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid?>("WinnerBidId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequesterId")
                        .HasDatabaseName("IX_TransportRequests_Requester");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_TransportRequests_Status");

                    b.ToTable("TransportRequests", (string)null);
                });

            modelBuilder.Entity("KrishiEye.Services.Transport.Domain.Entities.TransporterProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<int>("ServiceRadiusKm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(50);

                    b.Property<int>("TotalJobs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("TradeLicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TransporterProfiles", (string)null);
                });

            modelBuilder.Entity("KrishiEye.Services.Transport.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CapacityTon")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DocumentsUrl")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("FitnessExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ManufactureYear")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RegNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TransporterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("RegNumber")
                        .IsUnique();

                    b.HasIndex("TransporterId", "Status")
                        .HasDatabaseName("IX_Vehicles_Transporter_Status");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("KrishiEye.Services.Transport.Domain.Entities.Driver", b =>
                {
                    b.HasOne("KrishiEye.Services.Transport.Domain.Entities.TransporterProfile", "Transporter")
                        .WithMany("Drivers")
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transporter");
                });

            modelBuilder.Entity("KrishiEye.Services.Transport.Domain.Entities.JobAssignment", b =>
                {
                    b.HasOne("KrishiEye.Services.Transport.Domain.Entities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KrishiEye.Services.Transport.Domain.Entities.TransportRequest", "Request")
                        .WithOne("JobAssignment")
                        .HasForeignKey("KrishiEye.Services.Transport.Domain.Entities.JobAssignment", "RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KrishiEye.Services.Transport.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Request");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("KrishiEye.Services.Transport.Domain.Entities.TransportBid", b =>
                {
                    b.HasOne("KrishiEye.Services.Transport.Domain.Entities.TransportRequest", "Request")
                        .WithMany("Bids")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KrishiEye.Services.Transport.Domain.Entities.TransporterProfile", "Transporter")
                        .WithMany("Bids")
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("KrishiEye.Services.Transport.Domain.ValueObjects.Money", "BidAmount", b1 =>
                        {
                            b1.Property<Guid>("TransportBidId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("BidAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("BDT")
                                .HasColumnName("Currency");

                            b1.HasKey("TransportBidId");

                            b1.ToTable("TransportBids");

                            b1.WithOwner()
                                .HasForeignKey("TransportBidId");
                        });

                    b.Navigation("BidAmount")
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("Transporter");
                });

            modelBuilder.Entity("KrishiEye.Services.Transport.Domain.Entities.TransportRequest", b =>
                {
                    b.OwnsOne("KrishiEye.Services.Transport.Domain.ValueObjects.Location", "DropLocation", b1 =>
                        {
                            b1.Property<Guid>("TransportRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AddressLine")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("DropAddressLine");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("DropDistrict");

                            b1.Property<string>("Division")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("DropDivision");

                            b1.Property<decimal>("Latitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("DropLatitude");

                            b1.Property<decimal>("Longitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("DropLongitude");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("DropPostalCode");

                            b1.Property<string>("Thana")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("DropThana");

                            b1.HasKey("TransportRequestId");

                            b1.ToTable("TransportRequests");

                            b1.WithOwner()
                                .HasForeignKey("TransportRequestId");
                        });

                    b.OwnsOne("KrishiEye.Services.Transport.Domain.ValueObjects.Location", "PickupLocation", b1 =>
                        {
                            b1.Property<Guid>("TransportRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AddressLine")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("PickupAddressLine");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("PickupDistrict");

                            b1.Property<string>("Division")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("PickupDivision");

                            b1.Property<decimal>("Latitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("PickupLatitude");

                            b1.Property<decimal>("Longitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("PickupLongitude");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("PickupPostalCode");

                            b1.Property<string>("Thana")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("PickupThana");

                            b1.HasKey("TransportRequestId");

                            b1.HasIndex("District")
                                .HasDatabaseName("IX_TransportRequests_PickupDistrict");

                            b1.HasIndex("Latitude", "Longitude")
                                .HasDatabaseName("IX_TransportRequests_PickupLocation");

                            b1.ToTable("TransportRequests");

                            b1.WithOwner()
                                .HasForeignKey("TransportRequestId");
                        });

                    b.Navigation("DropLocation")
                        .IsRequired();

                    b.Navigation("PickupLocation")
                        .IsRequired();
                });

            modelBuilder.Entity("KrishiEye.Services.Transport.Domain.Entities.TransporterProfile", b =>
                {
                    b.OwnsOne("KrishiEye.Services.Transport.Domain.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("TransporterProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AddressLine")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("AddressLine");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("District");

                            b1.Property<string>("Division")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Division");

                            b1.Property<decimal>("Latitude")
                                .HasColumnType("numeric")
                                .HasColumnName("Latitude");

                            b1.Property<decimal>("Longitude")
                                .HasColumnType("numeric")
                                .HasColumnName("Longitude");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("PostalCode");

                            b1.Property<string>("Thana")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Thana");

                            b1.HasKey("TransporterProfileId");

                            b1.HasIndex("Latitude", "Longitude")
                                .HasDatabaseName("IX_TransporterProfiles_Location");

                            b1.ToTable("TransporterProfiles");

                            b1.WithOwner()
                                .HasForeignKey("TransporterProfileId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("KrishiEye.Services.Transport.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("KrishiEye.Services.Transport.Domain.Entities.TransporterProfile", "Transporter")
                        .WithMany("Vehicles")
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transporter");
                });

            modelBuilder.Entity("KrishiEye.Services.Transport.Domain.Entities.TransportRequest", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("JobAssignment");
                });

            modelBuilder.Entity("KrishiEye.Services.Transport.Domain.Entities.TransporterProfile", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("Drivers");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
